# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECPoVtapmWlcpsId1LJxSIw3RGSVqIuy
"""

import streamlit as st
import pandas as pd
import numpy as np
import requests
from datetime import date, timedelta
import plotly.express as px

# ==========================================
# 0. CONFIGURACIÓN DE LA PÁGINA
# ==========================================
st.set_page_config(page_title="Dashboard Carry Trade", layout="wide")
st.title("📊 Monitor de Carry Trade y Curva de Tasas")

# ==========================================
# 1. INPUTS DEL USUARIO (SIDEBAR)
# ==========================================
st.sidebar.header("Parámetros del Modelo")
mep = st.sidebar.number_input("Cotización MEP Inicial", value=1436.0, step=10.0)
base_fx = st.sidebar.number_input("Base FX (Banda)", value=1529.03, step=10.0)

fecha_hoy = pd.Timestamp(date.today())
anchor_date = pd.Timestamp(2026, 1, 1)

tickers = {
    "M27F6": date(2026, 2, 27),"S27F6": date(2026, 2, 27),
    "S16M6": date(2026, 3, 16), "S17A6": date(2026, 4, 17), "S30A6": date(2026, 4, 30),
    "S29Y6": date(2026, 5, 29), "T30J6": date(2026, 6, 30),"S31L6": date(2026, 7, 31), "T15E7": date(2027, 1, 15),
    "TTM26": date(2026, 3, 16), "TTJ26": date(2026, 6, 30), "M31G6": date(2026, 8, 31),
    "TTS26": date(2026, 9, 15), "S30O6": date(2026, 10, 30), "S30N6": date(2026, 11, 30),
    "TTD26": date(2026, 12, 15), "T30A7": date(2027, 4, 30), "T31Y7": date(2027, 5, 31)
}

payoff = {
    "M27F6": 122.630, "S27F6": 125.841, "S16M6": 104.621,
    "S17A6": 110.125, "S30A6": 127.486, "S29Y6": 132.043, "T30J6": 144.896, "S31L6": 117.608,
    "T15E7": 160.777, "TTM26": 149.706, "TTJ26": 160.280, "M31G6": 130.015,
    "TTS26": 167.496, "S30O6": 135.278, "S30N6": 130.282, "TTD26": 175.594,
    "T30A7": 157.341, "T31Y7": 152.042
}

# ==========================================
# 2. CACHEO DE DATOS DE API
# ==========================================
# Usamos cache_data para no saturar la API cada vez que movemos un parámetro
@st.cache_data(ttl=600) # Se actualiza cada 10 minutos
def fetch_market_data():
    notes = requests.get('https://data912.com/live/arg_notes').json()
    bonds = requests.get('https://data912.com/live/arg_bonds').json()
    return pd.DataFrame(notes + bonds)

# ==========================================
# 3. PROCESAMIENTO DE DATOS (Tu lógica)
# ==========================================
inflation_data = {
    'fecha_origen': [
        '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01',
        '2026-04-01', '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01'
    ],
    'tasa_mensual': [
        0.025, 0.028, 0.029, 0.021, 0.022, 0.019, 0.017, 0.016, 0.015, 0.014
    ]
}

df_curve = pd.DataFrame(inflation_data)
df_curve['fecha_impacto'] = pd.to_datetime(df_curve['fecha_origen']) + pd.DateOffset(months=2)

rango_dias = pd.date_range(start='2026-01-01', end='2027-06-01', freq='D')
df_daily = pd.DataFrame({'fecha': rango_dias})

df_daily = pd.merge_asof(df_daily, df_curve[['fecha_impacto', 'tasa_mensual']].sort_values('fecha_impacto'),
                         left_on='fecha', right_on='fecha_impacto', direction='backward')

df_daily['factor_diario'] = (1 + df_daily['tasa_mensual'])**(1/31)
df_daily['indice_raw'] = df_daily['factor_diario'].cumprod()
idx_base = df_daily.loc[df_daily['fecha'] == anchor_date, 'indice_raw'].values[0]
df_daily['banda_proyectada'] = base_fx * (df_daily['indice_raw'] / idx_base)

# Cargar datos desde la función cacheada
df_market = fetch_market_data()

carry = df_market.loc[df_market.symbol.isin(tickers.keys())].copy()
carry = carry.drop_duplicates(subset=['symbol'], keep='first')

carry['Precio'] = carry['c'].astype(float)
carry['Payoff'] = carry['symbol'].map(payoff)
carry['Vencimiento'] = pd.to_datetime(carry['symbol'].map(tickers))
carry['Dias'] = (carry['Vencimiento'] - fecha_hoy).dt.days.clip(lower=1)

carry['TNA'] = ((carry['Payoff'] / carry['Precio']) - 1) / carry['Dias'] * 365
carry['TEM'] = ((carry['Payoff'] / carry['Precio']) ** (30 / carry['Dias'])) - 1

carry = pd.merge_asof(carry.sort_values('Vencimiento'),
                      df_daily[['fecha', 'banda_proyectada']],
                      left_on='Vencimiento', right_on='fecha', direction='backward')

carry['Dolar_Breakeven'] = (mep * carry['Payoff']) / carry['Precio']
carry['Retorno_vs_Banda'] = (carry['Payoff'] / carry['Precio']) * (mep / carry['banda_proyectada']) - 1

escenarios_dolar = [1400, 1500, 1600, 1700]
cols_sensibilidad = []
for usd_px in escenarios_dolar:
    col_name = f'USD_{usd_px}'
    carry[col_name] = (carry['Payoff'] / carry['Precio']) * (mep / usd_px) - 1
    cols_sensibilidad.append(col_name)

# ==========================================
# 4. GRÁFICO: CURVA DE TASAS (PLOTLY)
# ==========================================
st.subheader("📈 Curva de Rendimientos (TNA)")

# Ordenamos para que la línea conecte bien los puntos
carry_plot = carry.sort_values('Vencimiento')

fig = px.scatter(
    carry_plot,
    x='Vencimiento',
    y='TNA',
    text='symbol',
    hover_data={'Precio': ':.2f', 'TEM': ':.2%', 'Dias': True, 'TNA': ':.2%'},
    trendline="lowess" # Opcional: añade una línea de tendencia suavizada
)
fig.update_traces(textposition='top center', marker=dict(size=10, color='blue'))
fig.update_layout(
    yaxis_tickformat='.1%',
    xaxis_title="Fecha de Vencimiento",
    yaxis_title="Tasa Nominal Anual (TNA)",
    height=500
)

st.plotly_chart(fig, use_container_width=True)

# ==========================================
# 5. TABLA: ANÁLISIS DE SENSIBILIDAD
# ==========================================
st.subheader("📋 Matriz de Sensibilidad y Carry")

cols_finales = ['symbol', 'Vencimiento', 'TNA','TEM', 'Dolar_Breakeven', 'banda_proyectada', 'Retorno_vs_Banda'] + cols_sensibilidad
df_final = carry[cols_finales].set_index('symbol').sort_values('Vencimiento')

# Aplicamos el estilo de Pandas
styled_df = df_final.style \
    .background_gradient(subset=['Retorno_vs_Banda'] + cols_sensibilidad,
                         cmap='RdYlGn', vmin=-0.10, vmax=0.15) \
    .format({
        'Vencimiento': '{:%d-%m-%Y}',
        'TNA': '{:.1%}',
        'TEM': '{:.1%}',
        'Dolar_Breakeven': '{:.0f}',
        'banda_proyectada': '{:.0f}',
        'Retorno_vs_Banda': '{:.1%}',
        **{col: '{:.1%}' for col in cols_sensibilidad}
    })

# Renderizamos en Streamlit
st.dataframe(styled_df, use_container_width=True, height=600)

import matplotlib.pyplot as plt
from datetime import datetime
# (Asegúrate de no duplicar los imports de numpy y pandas si ya están arriba)

st.divider() # Agrega una línea separadora visual en la app
st.subheader("📉 Estructura Temporal de Tasas (Matplotlib)")

# --- 1. CATEGORIZACIÓN ---
def categorizar(symbol):
    sym = str(symbol)
    if sym.startswith('S'):
        return 'Tasa Fija', '#1f77b4', 'o'  # Azul / Círculo
    if sym.startswith('TT'):
        return 'Tamar', '#d62728', 'D'     # Rojo / Diamante
    return 'Tasa Fija', '#2ca02c', '^'     # Verde / Triángulo

# Aplicamos la lógica sobre la columna 'symbol'
carry[['Categoria', 'Color', 'Marker']] = pd.DataFrame(
    carry['symbol'].apply(categorizar).tolist(), index=carry.index
)

# Ordenamos por días para la curva de tendencia
carry = carry.sort_values('Dias')

# --- 2. CONFIGURACIÓN DE ESTILO ---
# Agregamos un bloque try-except por si la versión de Matplotlib en la nube
# tiene un nombre ligeramente distinto para el estilo de seaborn.
try:
    plt.style.use('seaborn-v0_8-whitegrid')
except:
    plt.style.use('seaborn-whitegrid')

plt.rcParams.update({'font.sans-serif': ['Arial']})

fig, ax = plt.subplots(figsize=(11, 6.5))

# --- 3. CURVA DE TENDENCIA SUAVE ---
x = carry['Dias']
y = carry['TEM']
z = np.polyfit(x, y, 2)
p = np.poly1d(z)
x_range = np.linspace(x.min(), x.max(), 100)
ax.plot(x_range, p(x_range), color='gray', linestyle=':', linewidth=1.2, alpha=0.3, zorder=1)

# --- 4. DISPERSIÓN POR CATEGORÍA ---
for cat in carry['Categoria'].unique():
    df_cat = carry[carry['Categoria'] == cat]
    ax.scatter(df_cat['Dias'], df_cat['TEM'],
               color=df_cat['Color'].iloc[0],
               marker=df_cat['Marker'].iloc[0],
               s=110, label=cat, edgecolor='white', linewidth=0.7, zorder=3)

# --- 5. ETIQUETADO DE TICKERS (Offset dinámico) ---
for idx, row in carry.iterrows():
    ax.annotate(row['symbol'], (row['Dias'], row['TEM']),
                xytext=(0, 9), textcoords='offset points',
                fontsize=9, ha='center', fontweight='bold', alpha=0.7)

# --- 6. FORMATO Y CUADRO DE INFO ---
ax.set_title('Estructura Temporal de Tasas: TEM vs Plazo', fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Días al Vencimiento', fontweight='bold')
ax.set_ylabel('TEM (%)', fontweight='bold')

# Eje Y como porcentaje
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.2%}'))

# UBICACIÓN: Esquina inferior derecha
fecha_str = datetime.today().strftime("%d/%m/%Y")
info_box = f"Fecha: {fecha_str}\nMEP Inicial: ${mep:,.2f}" # Usamos el mep del st.sidebar
ax.text(0.98, 0.02, info_box, transform=ax.transAxes,
        fontsize=10, verticalalignment='bottom', horizontalalignment='right',
        bbox=dict(boxstyle="round,pad=0.5", facecolor='white', edgecolor='lightgray', alpha=0.7))

# Leyenda y limpieza de bordes
ax.legend(title="Instrumentos", frameon=True, loc='upper right', fontsize=10)
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)

plt.tight_layout()

# --- 7. RENDERIZADO EN STREAMLIT ---
# Reemplazamos plt.show() por st.pyplot()
st.pyplot(fig)

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.patheffects as pe
from matplotlib.dates import DateFormatter

st.divider()
st.subheader("🎯 Estrategia de Cobertura: Breakeven vs. Banda")

# --- 1. PREPARACIÓN DE DATOS ---
# Usamos df_daily para la línea continua y carry para los puntos específicos
df_banda = df_daily[(df_daily['fecha'] >= fecha_hoy) &
                    (df_daily['fecha'] <= carry['Vencimiento'].max() + pd.Timedelta(days=15))]
df_puntos = carry.sort_values('Vencimiento')

# --- 2. CONFIGURACIÓN ESTÉTICA ---
try:
    plt.style.use('seaborn-v0_8-whitegrid')
except:
    plt.style.use('seaborn-whitegrid')

fig2, ax2 = plt.subplots(figsize=(12, 7), dpi=250, facecolor='white')

# --- 3. PLOT DE LA BANDA (LÍNEA CONTINUA) ---
ax2.plot(df_banda['fecha'], df_banda['banda_proyectada'],
        color='#007acc', label='Proyección Banda (Inflación T-2)',
        linewidth=2.5, alpha=0.8, zorder=1)

# --- 4. PLOT DE BREAKEVENS (PUNTOS) ---
ax2.scatter(df_puntos['Vencimiento'], df_puntos['Dolar_Breakeven'],
           color='#f57c00', s=80, label='MEP Breakeven por Bono',
           edgecolor='white', linewidth=1, zorder=3)

# --- 5. ANOTACIONES DINÁMICAS ---
for _, row in df_puntos.iterrows():
    # Etiqueta del Bono (Arriba del punto)
    ax2.annotate(row['symbol'], (row['Vencimiento'], row['Dolar_Breakeven']),
                xytext=(0, 10), textcoords="offset points",
                ha='center', fontsize=9, fontweight='bold', color='#e65100',
                path_effects=[pe.withStroke(linewidth=2, foreground="white")])

    # Precio Breakeven (Debajo del punto)
    ax2.annotate(f'$ {row["Dolar_Breakeven"]:.0f}', (row['Vencimiento'], row['Dolar_Breakeven']),
                xytext=(0, -15), textcoords="offset points",
                ha='center', fontsize=8, color='black', fontweight='500',
                path_effects=[pe.withStroke(linewidth=2, foreground="white")])

# --- 6. FORMATO DE EJES Y ESTILO ---
ax2.set_title('Estrategia de Cobertura: MEP Breakeven vs. Banda de Inflación',
             fontsize=14, fontweight='bold', pad=20)

# Formato de Fecha en X
ax2.xaxis.set_major_formatter(DateFormatter("%b %y"))
# Al usar Streamlit, a veces plt.xticks afecta globalmente, es mejor usar ax2.tick_params
ax2.tick_params(axis='x', rotation=0)

# Formato de Miles en Y
ax2.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'${int(x):,}'))

# Cuadro de Info (Ubicación inferior derecha para no tapar)
info_text = f"MEP Hoy: ${mep:,.2f}\nBase Banda: ${base_fx:,.2f}"
ax2.text(0.97, 0.05, info_text, transform=ax2.transAxes,
        fontsize=9, va='bottom', ha='right',
        bbox=dict(boxstyle="round,pad=0.5", facecolor='white', edgecolor='lightgray', alpha=0.8))

# Estética Final
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.legend(loc='upper left', frameon=True, fontsize=10)
ax2.grid(axis='y', alpha=0.3)

plt.tight_layout()

# --- 7. RENDERIZADO EN STREAMLIT ---
st.pyplot(fig2)

import matplotlib.dates as mdates
from dateutil.relativedelta import relativedelta

st.divider()
st.subheader("🔮 Arbitraje: MEP vs Banda vs Dólar Futuro")

# --- 1. DATOS DE FUTUROS EDITABLES (ROFEX) ---
st.markdown("📝 **Edita las cotizaciones del Dólar Futuro directamente en esta tabla:**")

# Fechas base
fechas_futuro = pd.date_range(start='2026-02-01', periods=12, freq='ME')
valores_futuro_default = [1433, 1465, 1495, 1532, 1565, 1600, 1635, 1668, 1702, 1735, 1772, 1790]

# Creamos un DataFrame inicial para el editor
df_futuro_base = pd.DataFrame({
    'Fecha': fechas_futuro.date, # Mostramos solo la fecha sin la hora
    'Dolar_Futuro': valores_futuro_default
})

# El usuario edita esta tabla en la web
df_futuro_editado = st.data_editor(
    df_futuro_base,
    column_config={
        "Fecha": st.column_config.DateColumn("Vencimiento Rofex", disabled=True),
        "Dolar_Futuro": st.column_config.NumberColumn("Cotización ($)", min_value=1000, step=1, format="$%d")
    },
    hide_index=True,
    use_container_width=True
)

# Preparamos el DF editado para el gráfico
df_futuro = df_futuro_editado.copy()
df_futuro['Fecha'] = pd.to_datetime(df_futuro['Fecha'])

# --- 2. PREPARACIÓN Y FILTRADO ---
fecha_inicio = pd.Timestamp(2026, 3, 1)
fecha_fin = fecha_inicio + relativedelta(months=12)

# Normalizamos fechas
carry['Fecha'] = pd.to_datetime(carry['Vencimiento'])
carry_plot = carry[(carry['Fecha'] >= fecha_inicio) & (carry['Fecha'] <= fecha_fin)].copy()
df_banda_cont = df_daily[(df_daily['fecha'] >= fecha_inicio) & (df_daily['fecha'] <= fecha_fin)]

# --- 3. CONFIGURACIÓN VISUAL ---
try:
    plt.style.use('seaborn-v0_8-whitegrid')
except:
    plt.style.use('seaborn-whitegrid')

fig3, ax3 = plt.subplots(figsize=(14, 8), dpi=200, facecolor='white')
ax3.set_facecolor("white")

COLOR_BANDA = '#00bfff'   # Cyan
COLOR_FUTURO = '#1a237e'  # Navy
COLOR_MEP = '#ff6f00'     # Orange
stroke_white = [pe.withStroke(linewidth=3, foreground="white")]

# A. LÍNEA DE BANDA SUPERIOR
ax3.plot(df_banda_cont['fecha'], df_banda_cont['banda_proyectada'],
        color=COLOR_BANDA, label='Banda Superior (Inflación T-2)',
        linewidth=2.5, alpha=0.6, zorder=1)

# B. LÍNEA DE DÓLAR FUTURO (Con los datos que editó el usuario)
ax3.plot(df_futuro['Fecha'], df_futuro['Dolar_Futuro'],
        color=COLOR_FUTURO, linestyle='--', linewidth=2, label='Dólar Futuro (Rofex)',
        zorder=2)
ax3.scatter(df_futuro['Fecha'], df_futuro['Dolar_Futuro'],
           color=COLOR_FUTURO, s=40, marker='s', edgecolors='white', zorder=4)

# C. PUNTOS MEP BREAKEVEN
for i, (idx, row) in enumerate(carry_plot.sort_values('Fecha').iterrows()):
    fecha = row['Fecha']
    y_mep = row['Dolar_Breakeven']

    ax3.scatter(fecha, y_mep, color=COLOR_MEP, s=120, edgecolors='white',
               linewidth=1.5, zorder=5, label='MEP Breakeven' if i == 0 else "")

    offset = 20 if i % 2 == 0 else -30
    ax3.annotate(row['symbol'], (fecha, y_mep),
                xytext=(0, offset), textcoords="offset points",
                ha='center', fontsize=10, color=COLOR_MEP, weight='bold',
                path_effects=stroke_white)

    ax3.annotate(f'${y_mep:,.0f}', (fecha, y_mep),
                xytext=(0, offset - 12 if offset > 0 else offset + 12),
                textcoords="offset points", ha='center', fontsize=8,
                color='#333333', path_effects=stroke_white)

# --- ESTÉTICA FINAL ---
ax3.set_title('Arbitraje: MEP Breakeven vs Banda Inflación vs Dólar Futuro',
             fontsize=16, weight='bold', pad=25)

ax3.xaxis.set_major_locator(mdates.MonthLocator())
ax3.xaxis.set_major_formatter(mdates.DateFormatter('%b-%y'))
ax3.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'${int(x):,}'))

# Ajuste dinámico de escala
y_all = pd.concat([df_banda_cont['banda_proyectada'], df_futuro['Dolar_Futuro'], carry_plot['Dolar_Breakeven']])
ax3.set_ylim(y_all.min() * 0.97, y_all.max() * 1.05)

ax3.spines['top'].set_visible(False)
ax3.spines['right'].set_visible(False)
ax3.grid(True, axis='y', linestyle=':', alpha=0.5)
ax3.legend(loc='upper left', frameon=True, facecolor='white', framealpha=0.9)

plt.tight_layout()

# Renderizado en Streamlit
st.pyplot(fig3)