# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECPoVtapmWlcpsId1LJxSIw3RGSVqIuy
"""

import streamlit as st
import pandas as pd
import numpy as np
import requests
from datetime import date, timedelta
import plotly.express as px

# ==========================================
# 0. CONFIGURACIÓN DE LA PÁGINA
# ==========================================
st.set_page_config(page_title="Dashboard Carry Trade", layout="wide")
st.title("📊 Monitor de Carry Trade y Curva de Tasas")

# ==========================================
# 1. INPUTS DEL USUARIO (SIDEBAR)
# ==========================================
st.sidebar.header("Parámetros del Modelo")
mep = st.sidebar.number_input("Cotización MEP Inicial", value=1436.0, step=10.0)
base_fx = st.sidebar.number_input("Base FX (Banda)", value=1529.03, step=10.0)

fecha_hoy = pd.Timestamp(date.today())
anchor_date = pd.Timestamp(2026, 1, 1)

tickers = {
    "M27F6": date(2026, 2, 27),"S27F6": date(2026, 2, 27),
    "S16M6": date(2026, 3, 16), "S17A6": date(2026, 4, 17), "S30A6": date(2026, 4, 30),
    "S29Y6": date(2026, 5, 29), "T30J6": date(2026, 6, 30),"S31L6": date(2026, 7, 31), "T15E7": date(2027, 1, 15),
    "TTM26": date(2026, 3, 16), "TTJ26": date(2026, 6, 30), "M31G6": date(2026, 8, 31),
    "TTS26": date(2026, 9, 15), "S30O6": date(2026, 10, 30), "S30N6": date(2026, 11, 30),
    "TTD26": date(2026, 12, 15), "T30A7": date(2027, 4, 30), "T31Y7": date(2027, 5, 31)
}

payoff = {
    "M27F6": 122.630, "S27F6": 125.841, "S16M6": 104.621,
    "S17A6": 110.125, "S30A6": 127.486, "S29Y6": 132.043, "T30J6": 144.896, "S31L6": 117.608,
    "T15E7": 160.777, "TTM26": 149.706, "TTJ26": 160.280, "M31G6": 130.015,
    "TTS26": 167.496, "S30O6": 135.278, "S30N6": 130.282, "TTD26": 175.594,
    "T30A7": 157.341, "T31Y7": 152.042
}

# ==========================================
# 2. CACHEO DE DATOS DE API
# ==========================================
# Usamos cache_data para no saturar la API cada vez que movemos un parámetro
@st.cache_data(ttl=600) # Se actualiza cada 10 minutos
def fetch_market_data():
    notes = requests.get('https://data912.com/live/arg_notes').json()
    bonds = requests.get('https://data912.com/live/arg_bonds').json()
    return pd.DataFrame(notes + bonds)

# ==========================================
# 3. PROCESAMIENTO DE DATOS (Tu lógica)
# ==========================================
inflation_data = {
    'fecha_origen': [
        '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01',
        '2026-04-01', '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01'
    ],
    'tasa_mensual': [
        0.025, 0.028, 0.029, 0.021, 0.022, 0.019, 0.017, 0.016, 0.015, 0.014
    ]
}

df_curve = pd.DataFrame(inflation_data)
df_curve['fecha_impacto'] = pd.to_datetime(df_curve['fecha_origen']) + pd.DateOffset(months=2)

rango_dias = pd.date_range(start='2026-01-01', end='2027-06-01', freq='D')
df_daily = pd.DataFrame({'fecha': rango_dias})

df_daily = pd.merge_asof(df_daily, df_curve[['fecha_impacto', 'tasa_mensual']].sort_values('fecha_impacto'),
                         left_on='fecha', right_on='fecha_impacto', direction='backward')

df_daily['factor_diario'] = (1 + df_daily['tasa_mensual'])**(1/31)
df_daily['indice_raw'] = df_daily['factor_diario'].cumprod()
idx_base = df_daily.loc[df_daily['fecha'] == anchor_date, 'indice_raw'].values[0]
df_daily['banda_proyectada'] = base_fx * (df_daily['indice_raw'] / idx_base)

# Cargar datos desde la función cacheada
df_market = fetch_market_data()

carry = df_market.loc[df_market.symbol.isin(tickers.keys())].copy()
carry = carry.drop_duplicates(subset=['symbol'], keep='first')

carry['Precio'] = carry['c'].astype(float)
carry['Payoff'] = carry['symbol'].map(payoff)
carry['Vencimiento'] = pd.to_datetime(carry['symbol'].map(tickers))
carry['Dias'] = (carry['Vencimiento'] - fecha_hoy).dt.days.clip(lower=1)

carry['TNA'] = ((carry['Payoff'] / carry['Precio']) - 1) / carry['Dias'] * 365
carry['TEM'] = ((carry['Payoff'] / carry['Precio']) ** (30 / carry['Dias'])) - 1

carry = pd.merge_asof(carry.sort_values('Vencimiento'),
                      df_daily[['fecha', 'banda_proyectada']],
                      left_on='Vencimiento', right_on='fecha', direction='backward')

carry['Dolar_Breakeven'] = (mep * carry['Payoff']) / carry['Precio']
carry['Retorno_vs_Banda'] = (carry['Payoff'] / carry['Precio']) * (mep / carry['banda_proyectada']) - 1

escenarios_dolar = [1400, 1500, 1600, 1700]
cols_sensibilidad = []
for usd_px in escenarios_dolar:
    col_name = f'USD_{usd_px}'
    carry[col_name] = (carry['Payoff'] / carry['Precio']) * (mep / usd_px) - 1
    cols_sensibilidad.append(col_name)

# ==========================================
# 4. GRÁFICO: CURVA DE TASAS (PLOTLY)
# ==========================================
st.subheader("📈 Curva de Rendimientos (TNA)")

# Ordenamos para que la línea conecte bien los puntos
carry_plot = carry.sort_values('Vencimiento')

fig = px.scatter(
    carry_plot,
    x='Vencimiento',
    y='TNA',
    text='symbol',
    hover_data={'Precio': ':.2f', 'TEM': ':.2%', 'Dias': True, 'TNA': ':.2%'},
    trendline="lowess" # Opcional: añade una línea de tendencia suavizada
)
fig.update_traces(textposition='top center', marker=dict(size=10, color='blue'))
fig.update_layout(
    yaxis_tickformat='.1%',
    xaxis_title="Fecha de Vencimiento",
    yaxis_title="Tasa Nominal Anual (TNA)",
    height=500
)

st.plotly_chart(fig, use_container_width=True)

# ==========================================
# 5. TABLA: ANÁLISIS DE SENSIBILIDAD
# ==========================================
st.subheader("📋 Matriz de Sensibilidad y Carry")

cols_finales = ['symbol', 'Vencimiento', 'TNA','TEM', 'Dolar_Breakeven', 'banda_proyectada', 'Retorno_vs_Banda'] + cols_sensibilidad
df_final = carry[cols_finales].set_index('symbol').sort_values('Vencimiento')

# Aplicamos el estilo de Pandas
styled_df = df_final.style \
    .background_gradient(subset=['Retorno_vs_Banda'] + cols_sensibilidad,
                         cmap='RdYlGn', vmin=-0.10, vmax=0.15) \
    .format({
        'Vencimiento': '{:%d-%m-%Y}',
        'TNA': '{:.1%}',
        'TEM': '{:.1%}',
        'Dolar_Breakeven': '{:.0f}',
        'banda_proyectada': '{:.0f}',
        'Retorno_vs_Banda': '{:.1%}',
        **{col: '{:.1%}' for col in cols_sensibilidad}
    })

# Renderizamos en Streamlit
st.dataframe(styled_df, use_container_width=True, height=600)