# -*- coding: utf-8 -*-
"""Tasa Fija $ .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmmJH6fosh_DJ83DkqlVQD0WRJTaArVY
"""

import pandas as pd
import numpy as np
import requests
from datetime import date, timedelta

# ==========================================
# 1. CONFIGURACIÓN Y ANCLAJE
# ==========================================
mep = 1436
base_fx = 1529.03
fecha_hoy = pd.Timestamp(date.today())
anchor_date = pd.Timestamp(2026, 1, 1) # Anclamos la base al inicio de enero

tickers = {
    "M27F6": date(2026, 2, 27),"S27F6": date(2026, 2, 27),
    "S16M6": date(2026, 3, 16), "S17A6": date(2026, 4, 17), "S30A6": date(2026, 4, 30),
    "S29Y6": date(2026, 5, 29), "T30J6": date(2026, 6, 30),"S31L6": date(2026, 7, 31), "T15E7": date(2027, 1, 15),
    "TTM26": date(2026, 3, 16), "TTJ26": date(2026, 6, 30), "M31G6": date(2026, 8, 31),
    "TTS26": date(2026, 9, 15), "S30O6": date(2026, 10, 30), "S30N6": date(2026, 11, 30),
    "TTD26": date(2026, 12, 15), "T30A7": date(2027, 4, 30), "T31Y7": date(2027, 5, 31)
}

payoff = {
    "M27F6": 122.630, "S27F6": 125.841, "S16M6": 104.621,
    "S17A6": 110.125, "S30A6": 127.486, "S29Y6": 132.043, "T30J6": 144.896, "S31L6": 117.608,
    "T15E7": 160.777, "TTM26": 149.706, "TTJ26": 160.280, "M31G6": 130.015,
    "TTS26": 167.496, "S30O6": 135.278, "S30N6": 130.282, "TTD26": 175.594,
    "T30A7": 157.341, "T31Y7": 152.042
}

# ==========================================
# 2. CURVA DE INFLACIÓN (AJUSTADA PARA ENERO)
# ==========================================
inflation_data = {
    'fecha_origen': [
        '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01',
        '2026-04-01', '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01'
    ],
    'tasa_mensual': [
        0.025, 0.028, 0.029, 0.021, 0.022, 0.019, 0.017, 0.016, 0.015, 0.014
    ]
}

df_curve = pd.DataFrame(inflation_data)
df_curve['fecha_impacto'] = pd.to_datetime(df_curve['fecha_origen']) + pd.DateOffset(months=2)

rango_dias = pd.date_range(start='2026-01-01', end='2027-06-01', freq='D')
df_daily = pd.DataFrame({'fecha': rango_dias})

df_daily = pd.merge_asof(df_daily, df_curve[['fecha_impacto', 'tasa_mensual']].sort_values('fecha_impacto'),
                         left_on='fecha', right_on='fecha_impacto', direction='backward')

# Cálculo de banda con anclaje al 1 de enero
df_daily['factor_diario'] = (1 + df_daily['tasa_mensual'])**(1/31)
df_daily['indice_raw'] = df_daily['factor_diario'].cumprod()
idx_base = df_daily.loc[df_daily['fecha'] == anchor_date, 'indice_raw'].values[0]
df_daily['banda_proyectada'] = base_fx * (df_daily['indice_raw'] / idx_base)

# ... (Los bloques 1 y 2 de inflación y anclaje se mantienen iguales)

# ==========================================
# 3. OBTENCIÓN DE DATOS Y DEFINICIÓN DE 'CARRY'
# ==========================================
notes = requests.get('https://data912.com/live/arg_notes').json()
bonds = requests.get('https://data912.com/live/arg_bonds').json()
df_market = pd.DataFrame(notes + bonds)

# AQUÍ DEFINIMOS 'CARRY' PARA EVITAR EL NAMEERROR
carry = df_market.loc[df_market.symbol.isin(tickers.keys())].copy()
carry = carry.drop_duplicates(subset=['symbol'], keep='first')

# Variables básicas
carry['Precio'] = carry['c'].astype(float)
carry['Payoff'] = carry['symbol'].map(payoff)
carry['Vencimiento'] = pd.to_datetime(carry['symbol'].map(tickers))
carry['Dias'] = (carry['Vencimiento'] - fecha_hoy).dt.days.clip(lower=1)

# Métricas en Pesos
carry['TNA'] = ((carry['Payoff'] / carry['Precio']) - 1) / carry['Dias'] * 365
carry['TEM'] = ((carry['Payoff'] / carry['Precio']) ** (30 / carry['Dias'])) - 1

# Integración de Banda de Referencia
carry = pd.merge_asof(carry.sort_values('Vencimiento'),
                      df_daily[['fecha', 'banda_proyectada']],
                      left_on='Vencimiento', right_on='fecha', direction='backward')

carry['Dolar_Breakeven'] = (mep * carry['Payoff']) / carry['Precio']
carry['Retorno_vs_Banda'] = (carry['Payoff'] / carry['Precio']) * (mep / carry['banda_proyectada']) - 1

# ==========================================
# 4. ANÁLISIS DE SENSIBILIDAD (MAPA DE CALOR)
# ==========================================
escenarios_dolar = [1400, 1500, 1600, 1700]
cols_sensibilidad = []

for usd_px in escenarios_dolar:
    col_name = f'USD_{usd_px}'
    # Fórmula de retorno directo en USD vs MEP inicial
    carry[col_name] = (carry['Payoff'] / carry['Precio']) * (mep / usd_px) - 1
    cols_sensibilidad.append(col_name)

# ==========================================
# 5. VISUALIZACIÓN PROFESIONAL
# ==========================================
cols_finales = ['symbol', 'Vencimiento', 'TNA','TEM', 'Dolar_Breakeven', 'banda_proyectada', 'Retorno_vs_Banda'] + cols_sensibilidad
df_final = carry[cols_finales].set_index('symbol').sort_values('Vencimiento')

# Renderizado con estilo
df_final.style \
    .background_gradient(subset=['Retorno_vs_Banda'] + cols_sensibilidad,
                         cmap='RdYlGn', vmin=-0.10, vmax=0.15) \
    .format({
        'Vencimiento': '{:%d-%m-%Y}',
        'TNA': '{:.1%}',
        'TEM': '{:.1%}',
        'Dolar_Breakeven': '{:.0f}',
        'banda_proyectada': '{:.0f}',
        'Retorno_vs_Banda': '{:.1%}',
        **{col: '{:.1%}' for col in cols_sensibilidad}
    }) \
    .set_properties(**{'text-align': 'center'}) \
    .set_caption(f"Análisis de Carry Trade & Sensibilidad USD (MEP Inicial: {mep})")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import datetime

# --- 1. CATEGORIZACIÓN ---
def categorizar(symbol):
    sym = str(symbol)
    if sym.startswith('S'):
        return 'Tasa Fija', '#1f77b4', 'o'  # Azul / Círculo
    if sym.startswith('TT'):
        return 'Tamar', '#d62728', 'D'     # Rojo / Diamante
    return 'Tasa Fija', '#2ca02c', '^'           # Verde / Triángulo

# Aplicamos la lógica sobre la columna 'symbol'
carry[['Categoria', 'Color', 'Marker']] = pd.DataFrame(
    carry['symbol'].apply(categorizar).tolist(), index=carry.index
)

# Ordenamos por días para la curva de tendencia
carry = carry.sort_values('Dias')

# --- 2. CONFIGURACIÓN DE ESTILO ---
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({'font.sans-serif': ['Arial']})

fig, ax = plt.subplots(figsize=(11, 6.5))

# --- 3. CURVA DE TENDENCIA SUAVE ---
x = carry['Dias']
y = carry['TEM']
z = np.polyfit(x, y, 2)
p = np.poly1d(z)
x_range = np.linspace(x.min(), x.max(), 100)
ax.plot(x_range, p(x_range), color='gray', linestyle=':', linewidth=1.2, alpha=0.3, zorder=1)

# --- 4. DISPERSIÓN POR CATEGORÍA ---
for cat in carry['Categoria'].unique():
    df_cat = carry[carry['Categoria'] == cat]
    ax.scatter(df_cat['Dias'], df_cat['TEM'],
               color=df_cat['Color'].iloc[0],
               marker=df_cat['Marker'].iloc[0],
               s=110, label=cat, edgecolor='white', linewidth=0.7, zorder=3)

# --- 5. ETIQUETADO DE TICKERS (Offset dinámico) ---
for idx, row in carry.iterrows():
    ax.annotate(row['symbol'], (row['Dias'], row['TEM']),
                xytext=(0, 9), textcoords='offset points',
                fontsize=9, ha='center', fontweight='bold', alpha=0.7)

# --- 6. FORMATO Y CUADRO DE INFO (NUEVA UBICACIÓN) ---
ax.set_title('Estructura Temporal de Tasas: TEM vs Plazo', fontsize=16, pad=20, fontweight='bold')
ax.set_xlabel('Días al Vencimiento', fontweight='bold')
ax.set_ylabel('TEM (%)', fontweight='bold')

# Eje Y como porcentaje
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.2%}'))

# UBICACIÓN: Esquina inferior derecha (ha='right', va='bottom') para que no tape los puntos
fecha_str = datetime.today().strftime("%d/%m/%Y")
info_box = f"Fecha: {fecha_str}\nMEP: ${mep:,.2f}"
ax.text(0.98, 0.02, info_box, transform=ax.transAxes,
        fontsize=10, verticalalignment='bottom', horizontalalignment='right',
        bbox=dict(boxstyle="round,pad=0.5", facecolor='white', edgecolor='lightgray', alpha=0.7))

# Leyenda y limpieza de bordes
ax.legend(title="Instrumentos", frameon=True, loc='upper right', fontsize=10)
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.patheffects as pe
from matplotlib.dates import DateFormatter

# --- 1. PREPARACIÓN DE DATOS ---
# Usamos df_daily para la línea continua y carry para los puntos específicos
df_banda = df_daily[(df_daily['fecha'] >= fecha_hoy) &
                    (df_daily['fecha'] <= carry['Vencimiento'].max() + pd.Timedelta(days=15))]
df_puntos = carry.sort_values('Vencimiento')

# --- 2. CONFIGURACIÓN ESTÉTICA ---
plt.style.use('seaborn-v0_8-whitegrid')
fig, ax = plt.subplots(figsize=(12, 7), dpi=250, facecolor='white')

# --- 3. PLOT DE LA BANDA (LÍNEA CONTINUA) ---
ax.plot(df_banda['fecha'], df_banda['banda_proyectada'],
        color='#007acc', label='Proyección Banda (Inflación T-2)',
        linewidth=2.5, alpha=0.8, zorder=1)

# --- 4. PLOT DE BREAKEVENS (PUNTOS) ---
ax.scatter(df_puntos['Vencimiento'], df_puntos['Dolar_Breakeven'],
           color='#f57c00', s=80, label='MEP Breakeven por Bono',
           edgecolor='white', linewidth=1, zorder=3)

# --- 5. ANOTACIONES DINÁMICAS ---
for _, row in df_puntos.iterrows():
    # Etiqueta del Bono (Arriba del punto)
    ax.annotate(row['symbol'], (row['Vencimiento'], row['Dolar_Breakeven']),
                xytext=(0, 10), textcoords="offset points",
                ha='center', fontsize=9, fontweight='bold', color='#e65100',
                path_effects=[pe.withStroke(linewidth=2, foreground="white")])

    # Precio Breakeven (Debajo del punto)
    ax.annotate(f'$ {row["Dolar_Breakeven"]:.0f}', (row['Vencimiento'], row['Dolar_Breakeven']),
                xytext=(0, -15), textcoords="offset points",
                ha='center', fontsize=8, color='black', fontweight='500',
                path_effects=[pe.withStroke(linewidth=2, foreground="white")])

# --- 6. FORMATO DE EJES Y ESTILO ---
ax.set_title('Estrategia de Cobertura: MEP Breakeven vs. Banda de Inflación',
             fontsize=14, fontweight='bold', pad=20)

# Formato de Fecha en X
ax.xaxis.set_major_formatter(DateFormatter("%b %y"))
plt.xticks(rotation=0, ha='center')

# Formato de Miles en Y
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'${int(x):,}'))

# Cuadro de Info (Ubicación inferior derecha para no tapar)
info_text = f"MEP Hoy: ${mep:,.2f}\nBase Banda: ${base_fx:,.2f}"
ax.text(0.97, 0.05, info_text, transform=ax.transAxes,
        fontsize=9, va='bottom', ha='right',
        bbox=dict(boxstyle="round,pad=0.5", facecolor='white', edgecolor='lightgray', alpha=0.8))

# Estética Final
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.legend(loc='upper left', frameon=True, fontsize=10)
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('grafico_breakeven_final.png', dpi=300, bbox_inches='tight')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
import matplotlib.ticker as ticker
import matplotlib.dates as mdates
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

# --- 1. DATOS DE FUTUROS (ROFEX) ---
fechas_futuro = pd.date_range(start='2026-02-01', periods=12, freq='ME')
# Valores actualizados (ejemplo)
valores_futuro = [1433, 1465, 1495, 1532, 1565, 1600, 1635, 1668, 1702, 1735, 1772, 1790]
df_futuro = pd.DataFrame({'Fecha': fechas_futuro, 'Dolar_Futuro': valores_futuro})

# --- 2. PREPARACIÓN Y FILTRADO ---
fecha_inicio = pd.Timestamp(2026, 3, 1)
fecha_fin = fecha_inicio + relativedelta(months=12)

# Normalizamos fechas en carry y df_daily (el de los códigos anteriores)
carry['Fecha'] = pd.to_datetime(carry['Vencimiento'])
carry_plot = carry[(carry['Fecha'] >= fecha_inicio) & (carry['Fecha'] <= fecha_fin)].copy()

# Usamos el df_daily que creamos en el Código 2 para la línea continua de la banda
df_banda_cont = df_daily[(df_daily['fecha'] >= fecha_inicio) & (df_daily['fecha'] <= fecha_fin)]

# --- 3. CONFIGURACIÓN VISUAL ---
plt.style.use('seaborn-v0_8-whitegrid')
fig, ax = plt.subplots(figsize=(14, 8), dpi=200, facecolor='white')
ax.set_facecolor("white")

# Colores institucionales
COLOR_BANDA = '#00bfff'   # Cyan (Inflación)
COLOR_FUTURO = '#1a237e'  # Navy (Mercado)
COLOR_MEP = '#ff6f00'     # Orange (Bonos)
stroke_white = [pe.withStroke(linewidth=3, foreground="white")]

# -------------------------------------------------------------------------
# A. LÍNEA DE BANDA SUPERIOR (DRIFT INFLACIONARIO)
# -------------------------------------------------------------------------
ax.plot(df_banda_cont['fecha'], df_banda_cont['banda_proyectada'],
        color=COLOR_BANDA, label='Banda Superior (Inflación T-2)',
        linewidth=2.5, alpha=0.6, zorder=1)

# -------------------------------------------------------------------------
# B. LÍNEA DE DÓLAR FUTURO (EXPECTATIVA DE MERCADO)
# -------------------------------------------------------------------------
ax.plot(df_futuro['Fecha'], df_futuro['Dolar_Futuro'],
        color=COLOR_FUTURO, linestyle='--', linewidth=2, label='Dólar Futuro (Rofex)',
        zorder=2)
ax.scatter(df_futuro['Fecha'], df_futuro['Dolar_Futuro'],
           color=COLOR_FUTURO, s=40, marker='s', edgecolors='white', zorder=4)

# -------------------------------------------------------------------------
# C. PUNTOS MEP BREAKEVEN (TUS BONOS)
# -------------------------------------------------------------------------
for i, (idx, row) in enumerate(carry_plot.sort_values('Fecha').iterrows()):
    fecha = row['Fecha']
    y_mep = row['Dolar_Breakeven']

    # Punto del bono
    ax.scatter(fecha, y_mep, color=COLOR_MEP, s=120, edgecolors='white',
               linewidth=1.5, zorder=5, label='MEP Breakeven' if i == 0 else "")

    # Ticker con alternancia para evitar solapamiento
    offset = 20 if i % 2 == 0 else -30
    ax.annotate(row['symbol'], (fecha, y_mep),
                xytext=(0, offset), textcoords="offset points",
                ha='center', fontsize=10, color=COLOR_MEP, weight='bold',
                path_effects=stroke_white)

    # Precio Breakeven
    ax.annotate(f'${y_mep:,.0f}', (fecha, y_mep),
                xytext=(0, offset - 12 if offset > 0 else offset + 12),
                textcoords="offset points", ha='center', fontsize=8,
                color='#333333', path_effects=stroke_white)

# -------------------------------------------------------------------------
# ESTÉTICA FINAL
# -------------------------------------------------------------------------
ax.set_title('Arbitraje: MEP Breakeven vs Banda Inflación vs Dólar Futuro',
             fontsize=16, weight='bold', pad=25)

# Formato de Ejes
ax.xaxis.set_major_locator(mdates.MonthLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b-%y'))
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'${int(x):,}'))

# Ajuste dinámico de escala
y_all = pd.concat([df_banda_cont['banda_proyectada'], df_futuro['Dolar_Futuro'], carry_plot['Dolar_Breakeven']])
ax.set_ylim(y_all.min() * 0.97, y_all.max() * 1.05)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(True, axis='y', linestyle=':', alpha=0.5)

ax.legend(loc='upper left', frameon=True, facecolor='white', framealpha=0.9)

plt.tight_layout()
plt.show()